const images = {
  arrow: require("../../../assets/images/arrow.png"),
  wardrobe: require("../../../assets/images/wardrobe.png"),
  clothes: {
    cap: require("../../../assets/images/clothes/cap.png"),
    hoodie: require("../../../assets/images/clothes/hoodie.png"),
    shoes: require("../../../assets/images/clothes/shoes.png"),
    socket: require("../../../assets/images/clothes/socket.png"),
    top: require("../../../assets/images/clothes/top.png"),
    trousers: require("../../../assets/images/clothes/trousers.png"),
  },
  brand: {
    cap_n: require("../../../assets/images/clothes/cap_n.png"),
    cap_nf: require("../../../assets/images/clothes/cap_nf.png"),
    cap_rl: require("../../../assets/images/clothes/cap_rl.png"),
    hoodie_w: require("../../../assets/images/clothes/hoodie_w.png"),
    hoodie_c: require("../../../assets/images/clothes/hoodie_c.png"),
    hoodie_n: require("../../../assets/images/clothes/hoodie_n.png"),
    jacket_c: require("../../../assets/images/clothes/jacket_c.png"),
    jacket_l: require("../../../assets/images/clothes/jacket_l.png"),
    jacket_nf: require("../../../assets/images/clothes/jacket_nf.png"),
    shoes_c: require("../../../assets/images/clothes/shoes_c.png"),
    shoes_cv: require("../../../assets/images/clothes/shoes_cv.png"),
    shoes_dm: require("../../../assets/images/clothes/shoes_dm.png"),
    shoes_b: require("../../../assets/images/clothes/shoes_b.png"),
    shoes_n: require("../../../assets/images/clothes/shoes_n.png"),
    shoes_v: require("../../../assets/images/clothes/shoes_v.png"),
    short_w: require("../../../assets/images/clothes/short_w.png"),
    short_w2: require("../../../assets/images/clothes/short_w2.png"),
    socks_c: require("../../../assets/images/clothes/socks_c.png"),
    socks_n: require("../../../assets/images/clothes/socks_n.png"),
    top_b: require("../../../assets/images/clothes/top_b.png"),
    top_jj: require("../../../assets/images/clothes/top_jj.png"),
    trousers_l: require("../../../assets/images/clothes/trousers_l.png"),
    trousers_af: require("../../../assets/images/clothes/trousers_af.png"),
    trousers_c: require("../../../assets/images/clothes/trousers_c.png"),
    trousers_pb: require("../../../assets/images/clothes/trousers_pb.png"),
    tshirt_pl: require("../../../assets/images/clothes/tshirt_pl.png"),
    tshirt_w: require("../../../assets/images/clothes/tshirt_w.png"),
    tshirt_w2: require("../../../assets/images/clothes/tshirt_w2.png"),
  },
};

export default images;
